version: "2"

services:
  nginx:
    image: ghcr.io/groskopf/printerboks_nginx:1.2
    container_name: printerboks_nginx
    networks:
      - printerboks_network
    env_file:
      - ./config.env
    volumes:
      - nginx_conf:/etc/nginx/sites
      - nginx_ssl:/etc/nginx/ssl
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: ghcr.io/groskopf/printerboks_certbot:1.1
    container_name: printerboks_certbot
    networks:
      - printerboks_network
    env_file:
      - ./config.env
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot

  api:
    image: ghcr.io/groskopf/printerbox_pdf:1.3
    container_name: printerbox_pdf
    depends_on:
      - nginx
    ports:
      - "8000:8000"
    networks:
      - printerboks_network
    volumes:
      - images:/app/images
      - sheets:/app/sheets
      - name_tags:/app/name_tags
      - bookings:/app/bookings
      - config:/app/config
      - keys:/app/keys
    restart: always

  cron:
    image: ghcr.io/groskopf/printerboks_certbot_cron:1.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro

        #  cleanup:
        #    build: ./cleanup
        #    image: ghcr.io/groskopf/printerboks_cleanup:0.2
        #    volumes:
        #      - images:/workdir/images
        #      - sheets:/workdir/sheets
        #      - name_tags:/workdir/name_tags
        #    restart: always

volumes:
  nginx_conf:
  nginx_ssl:
    external: true
  letsencrypt_certs:
    external: true
  certbot_acme_challenge:
  images:
    external: true
  name_tags:
    external: true
  sheets:
    external: true
  bookings:
    external: true
  keys:
    external: true
  config:
    external: true

networks:
  printerboks_network:
    driver: bridge

